/**
 * Configuration for the Get Eligibility endpoint
 */
export default {
  uuid: "e17b35bc-24b7-4e6e-a4d9-a08278d7bd98",
  type: "http",
  documentation: "Get Eligibility",
  method: "get",
  endpoint: "credit/1.0/underwriting/transactioninstalment/user",
  responses: [
    {
      uuid: "5440c285-3482-48a3-b266-32b03ab5f269",
      body: "{}",
      latency: 1000,
      statusCode: 404,
      label: "",
      headers: [],
      bodyType: "INLINE",
      filePath: "",
      databucketID: "",
      sendFileAsBody: false,
      rules: [],
      rulesOperator: "OR",
      disableTemplating: false,
      fallbackTo404: false,
      default: false,
    },
    {
      uuid: "a2e5269e-7187-4062-8af6-ae9bd034a8ac",
      body: JSON.stringify(
        {
          max_loan_amount: "$5000.00",
          min_loan_amount: "$100.00",
          fees: [
            {
              duration: 3,
              percentage: 15,
              amount: "$11.25",
              name: "3-month instalment fee",
            },
            {
              duration: 6,
              percentage: 20,
              amount: "$20.00",
              name: "6-month instalment fee",
            },
            {
              duration: 9,
              percentage: 25,
              amount: "$25.00",
              name: "9-month instalment fee",
            },
          ],
          interest_rate: 15,
          eligibility_result: "NOT_ELIGIBLE",
        },
        null,
        2
      ),
      latency: 0,
      statusCode: 200,
      label: "NOT_ELIGIBLE",
      headers: [],
      bodyType: "INLINE",
      filePath: "",
      databucketID: "",
      sendFileAsBody: false,
      rules: [],
      rulesOperator: "OR",
      disableTemplating: false,
      fallbackTo404: false,
      default: false,
    },
    {
      uuid: "31bfc3f2-b8bb-4dd5-9beb-9af39dcf3437",
      body: JSON.stringify(
        {
          max_loan_amount: "$5000.00",
          min_loan_amount: "$100.00",
          fees: [
            {
              duration: 3,
              percentage: 15,
              amount: "$11.25",
              name: "3-month instalment fee",
            },
            {
              duration: 6,
              percentage: 20,
              amount: "$20.00",
              name: "6-month instalment fee",
            },
            {
              duration: 9,
              percentage: 25,
              amount: "$25.00",
              name: "9-month instalment fee",
            },
          ],
          interest_rate: 15,
          eligibility_result: "ELIGIBLE",
        },
        null,
        2
      ),
      latency: 0,
      statusCode: 200,
      label: "ELIGIBLE",
      headers: [],
      bodyType: "INLINE",
      filePath: "",
      databucketID: "",
      sendFileAsBody: false,
      rules: [],
      rulesOperator: "OR",
      disableTemplating: false,
      fallbackTo404: false,
      default: true,
    },
  ],
};
